name: Reset pkgrel in PKGBUILD

on:
  pull_request:
    paths:
      - '*/PKGBUILD'
    branches:
      - main

jobs:
  reset-pkgrel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Find updated package
        id: getPackage
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "package=$(git diff --name-only HEAD HEAD~1 "*/PKGBUILD" | head -1 | xargs dirname)" | tee -a "$GITHUB_OUTPUT"


      - name: Reset pkgrel
        id: resetPkgrel
        if: ${{ steps.getPackage.outputs.package != '' }}
        env:
          PACKAGE: ${{ steps.getPackage.outputs.package }}
        run: |
          [[ "$RUNNER_DEBUG" == 1 ]] && set -x

          set -euo pipefail

          if git cat-file -e origin/main:"$PACKAGE/PKGBUILD" && git diff origin/main "$PACKAGE/PKGBUILD" | grep -q pkgver; then
            sed -i -r 's#^pkgrel=[0-9]+#pkgrel=1#g' "$PACKAGE/PKGBUILD"
            echo changed=true | tee -a "$GITHUB_OUTPUT"
          else
            echo changed=false | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Commit PKGBUILD
        if: ${{ steps.resetPkgrel.outputs.changed == 'true' }}
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          message: "ci: [bot] Reset pkgrel"
          default_author: github_actions
          push: true
          add: ${{ steps.getPackage.outputs.package }}/PKGBUILD
