name: Validate PKGBUILD

on:
  pull_request:
    paths:
      - '*/PKGBUILD'
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        id: getPackage
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "package=$(git diff --name-only HEAD HEAD~1 "*/PKGBUILD" | head -1 | xargs dirname)" | tee -a "$GITHUB_OUTPUT"


      - name: Validate package
        if: ${{ steps.getPackage.outputs.package != '' }}
        uses: ./.github/actions/aur
        with:
          action: validate
          pkgname: ${{ steps.getPackage.outputs.package }}
          aur_email: ${{ secrets.AUR_EMAIL }}
          aur_username: ${{ secrets.AUR_USERNAME }}
